packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@medusajs/telemetry': true
  '@swc/core': true
  better-sqlite3: set this to true or false
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
