packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@medusajs/telemetry': true
  '@scarf/scarf': false
  '@swc/core': true
  better-sqlite3: set this to true or false
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  '@medusajs/js-sdk@2.17.0': patches/@medusajs__js-sdk@2.17.0.patch
